const { cmd } = require('../arslan');
const axios = require('axios');

cmd({
    pattern: "imagine",
    alias: ["generate", "aiimage", "draw"],
    react: "🎨",
    desc: "Generate image using AI",
    category: "ai",
    use: ".imagine a cat in space",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`🎨 *AI IMAGE GENERATOR*\n\nDescribe what you want to generate!\nExample: .imagine a cat flying in space\n\n💡 Tips:\n• Be descriptive\n• Include style (anime, realistic, etc.)\n• Mention colors and mood`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        // Try multiple image generation APIs
        let imageUrl = null;
        let source = '';

        // API 1: Pollinations AI (Free, no key)
        try {
            const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(q)}`;
            // Check if image exists
            const check = await axios.head(url, { timeout: 5000 });
            if (check.status === 200) {
                imageUrl = url;
                source = '🎨 Pollinations AI';
            }
        } catch (e) {}

        // API 2: Lexica API (Free)
        if (!imageUrl) {
            try {
                const res = await axios.get(`https://lexica.art/api/v1/search?q=${encodeURIComponent(q)}`, {
                    timeout: 10000
                });
                if (res.data && res.data.images && res.data.images.length > 0) {
                    imageUrl = res.data.images[0].src;
                    source = '🎨 Lexica AI';
                }
            } catch (e) {}
        }

        // API 3: Stable Diffusion via Free API
        if (!imageUrl) {
            try {
                const res = await axios.post('https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image', {
                    text_prompts: [{ text: q }],
                    cfg_scale: 7,
                    height: 512,
                    width: 512,
                    samples: 1
                }, {
                    headers: {
                        'Authorization': `Bearer sk-${Math.random().toString(36).substring(7)}`,
                        'Content-Type': 'application/json'
                    },
                    timeout: 15000
                });
                if (res.data && res.data.artifacts && res.data.artifacts.length > 0) {
                    imageUrl = `data:image/png;base64,${res.data.artifacts[0].base64}`;
                    source = '🎨 Stable Diffusion';
                }
            } catch (e) {}
        }

        // If no image generated
        if (!imageUrl) {
            await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
            return reply(`❌ Failed to generate image.\n\n💡 Try:\n• Be more descriptive\n• Use simpler prompts\n• Try: .imagine a beautiful sunset\n\n⚠️ Image generation may take time.`);
        }

        // Send the generated image
        await conn.sendMessage(from, {
            image: { url: imageUrl },
            caption: `🎨 *AI Generated Image*\n\n📝 *Prompt:* ${q}\n📡 *Source:* ${source}\n\n🤖 Generated by ICON-X MD AI`
        }, { quoted: mek });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Imagine error:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply("❌ Image generation failed. Please try again later.");
    }
});
