const { cmd } = require('../arslan');
const mumaker = require('mumaker');
const config = require('../config');

cmd({
    pattern: "arena",
    alias: [],
    desc: "Create arena text effect",
    category: "textmaker",
    use: ".arena <text>",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`🎨 *ARENA TEXT EFFECT*\n\nCreate arena text effect!\nExample: .arena Nick`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        const result = await mumaker.ephoto('https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html', q);

        if (!result || !result.image) {
            throw new Error('No image URL received from the API');
        }

        await conn.sendMessage(from, {
            image: { url: result.image },
            caption: `🎨 *Arena Text Effect*\n\n📝 *Text:* ${q}\n📡 Generated by ${config.botName || 'ICON-X MD'}`
        }, { quoted: m });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Error in arena command:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply(`❌ Error: ${error.message}`);
    }
});