const { cmd } = require('../arslan');
const mumaker = require('mumaker');
const config = require('../config');

cmd({
    pattern: "glitch",
    alias: [],
    desc: "Create glitch text effect",
    category: "textmaker",
    use: ".glitch <text>",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`🎨 *GLITCH TEXT EFFECT*\n\nCreate glitch text effect!\nExample: .glitch Nick`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        const result = await mumaker.ephoto('https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html', q);

        if (!result || !result.image) {
            throw new Error('No image URL received from the API');
        }

        await conn.sendMessage(from, {
            image: { url: result.image },
            caption: `🎨 *Glitch Text Effect*\n\n📝 *Text:* ${q}\n📡 Generated by ${config.botName || 'ICON-X MD'}`
        }, { quoted: m });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Error in glitch command:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply(`❌ Error: ${error.message}`);
    }
});