const { cmd } = require('../arslan');
const mumaker = require('mumaker');
const config = require('../config');

cmd({
    pattern: "ice",
    alias: [],
    desc: "Create ice text effect",
    category: "textmaker",
    use: ".ice <text>",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`❄️ *ICE TEXT EFFECT*\n\nCreate ice text effect!\nExample: .ice Nick`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        const result = await mumaker.ephoto('https://en.ephoto360.com/ice-text-effect-online-101.html', q);

        if (!result || !result.image) {
            throw new Error('No image URL received from the API');
        }

        await conn.sendMessage(from, {
            image: { url: result.image },
            caption: `❄️ *Ice Text Effect*\n\n📝 *Text:* ${q}\n📡 Generated by ${config.botName || 'ICON-X MD'}`
        }, { quoted: m });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Error in ice command:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply(`❌ Error: ${error.message}`);
    }
});