const { cmd } = require('../arslan');
const mumaker = require('mumaker');
const config = require('../config');

cmd({
    pattern: "light",
    alias: [],
    desc: "Create light text effect",
    category: "textmaker",
    use: ".light <text>",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`💡 *LIGHT TEXT EFFECT*\n\nCreate light text effect!\nExample: .light Nick`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        const result = await mumaker.ephoto('https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html', q);

        if (!result || !result.image) {
            throw new Error('No image URL received from the API');
        }

        await conn.sendMessage(from, {
            image: { url: result.image },
            caption: `💡 *Light Text Effect*\n\n📝 *Text:* ${q}\n📡 Generated by ${config.botName || 'ICON-X MD'}`
        }, { quoted: m });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Error in light command:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply(`❌ Error: ${error.message}`);
    }
});