const { cmd } = require('../../arslan');
const mumaker = require('mumaker');
const config = require('../config');

cmd({
    pattern: "snow",
    alias: [],
    desc: "Create snow text effect",
    category: "textmaker",
    use: ".snow <text>",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        if (!q) {
            return reply(`❄️ *SNOW TEXT EFFECT*\n\nCreate snow text effect!\nExample: .snow Nick`);
        }

        await conn.sendMessage(from, { react: { text: "⏳", key: mek.key } });

        const result = await mumaker.ephoto('https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html', q);

        if (!result || !result.image) {
            throw new Error('No image URL received from the API');
        }

        await conn.sendMessage(from, {
            image: { url: result.image },
            caption: `❄️ *Snow Text Effect*\n\n📝 *Text:* ${q}\n📡 Generated by ${config.botName || 'ICON-X MD'}`
        }, { quoted: m });

        await conn.sendMessage(from, { react: { text: "✅", key: mek.key } });

    } catch (error) {
        console.error("Error in snow command:", error);
        await conn.sendMessage(from, { react: { text: "❌", key: mek.key } });
        reply(`❌ Error: ${error.message}`);
    }
});